<Project>
  <PropertyGroup>
    <Authors>irusanov, LenovoLegionToolkit-Team</Authors>
    <Copyright>Copyright © 2026</Copyright>
    <RepositoryUrl>https://github.com/LenovoLegionToolkit-Team/ZenStates-Core</RepositoryUrl>
    <PackageProjectUrl>https://github.com/LenovoLegionToolkit-Team/ZenStates-Core</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
