<Project>
  <PropertyGroup>
    <VersionMajor>1</VersionMajor>
    <VersionMinor>92</VersionMinor>
    <VersionBase>$(VersionMajor).$(VersionMinor)</VersionBase>
    <Authors>irusanov, LenovoLegionToolkit-Team</Authors>
    <Copyright>Copyright © 2026</Copyright>
    <RepositoryUrl>https://github.com/LenovoLegionToolkit-Team/ZenStates-Core</RepositoryUrl>
    <PackageProjectUrl>https://github.com/LenovoLegionToolkit-Team/ZenStates-Core</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
