<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>ZenStates.Core</RootNamespace>
    <TargetFrameworks>net9.0-windows</TargetFrameworks>
    <AssemblyTitle>ZenStates.Core</AssemblyTitle>
    <PackageId>LLT.ZenStates-Core</PackageId>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Description>Slim build of ZenStates-Core for Lenovo Legion Toolkit.</Description>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon />
    <ErrorReport>none</ErrorReport>
  </PropertyGroup>
  <PropertyGroup>
    <WarningLevel>4</WarningLevel>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Cpu.cs" />
    <Compile Include="SMU.cs" />
    <Compile Include="Utils.cs" />
    <Compile Include="Constants.cs" />
    <Compile Include="CpuInitSettings.cs" />
    <Compile Include="PowerTable.cs" />
    <Compile Include="AgesaUtils.cs" />
    <Compile Include="WMI.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="PawnIo\PawnIo.cs" />
    <Compile Include="PawnIo\RyzenSmu.cs" />
    <Compile Include="PawnIo\AmdFamily17.cs" />
    <Compile Include="Mailbox\Mailbox.cs" />
    <Compile Include="Mailbox\RSMUMailbox.cs" />
    <Compile Include="Mailbox\MP1Mailbox.cs" />
    <Compile Include="Mailbox\HSMPMailbox.cs" />
    <Compile Include="Mailbox\GpuMailbox.cs" />
    <Compile Include="SMUSettings\*.cs" />
    <Compile Include="SMUCommands\*.cs" />
    <Compile Include="Mutex\Mutexes.cs" />
    <Compile Include="Mutex\PciBusLock.cs" />
    <Compile Include="OHWM\Opcode.cs" />
    <Compile Include="OHWM\OperatingSystem.cs" />
    <Compile Include="OHWM\GroupAffinity.cs" />
    <Compile Include="OHWM\ThreadAffinity.cs" />
    <Compile Include="Slim\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\PawnIo\RyzenSMU.bin" />
    <EmbeddedResource Include="Resources\PawnIo\AMDFamily17.bin" />
  </ItemGroup>
  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="\" CopyToOutputDirectory="Always" />
    <None Include="README.md" Pack="true" PackagePath="\" CopyToOutputDirectory="Always" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="6.0.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="6.0.0" />
    <PackageReference Include="System.Threading.AccessControl" Version="6.0.0" />
  </ItemGroup>
</Project>
